# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/portail_etudiant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=abass
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

# SQL init (data.sql)
spring.sql.init.mode=always

server.port=8080
spring.thymeleaf.cache=false